### ISSUE TITLE
Doesn't work for MadCatz drum brain

### ISSUE THREAD

**Issue by DrkCloudStrife** [delabrcd/rockband-4-midi-drums#1]
First of all, thank you so much for putting this together! I have been looking for a way to use an electronic drum kit with my Xbox without having to spend an arm and a leg on an adapter, or having to learn hardware engineering 😓 

I'm writing this issue to keep track of something I encountered while programming my Arduino board for the MadCatz drum brain.

## The Issue

The existing configuration for the Arduino doesn't seem to work with the Mad Catz drum brain.

---

## Additional Info

I found out that there are two types of Rock Band 4 Drum brains. One is the PDP, which is the one this is configured for, and the other is MadCatz. I have the MadCatz drum brain and had to make some alterations to the code. I have a mess in a branch https://github.com/DrkCloudStrife/rockband-4-midi-drums/compare/master...DrkCloudStrife:rockband-4-midi-drums:madcatz-rb4-config?expand=1, and I'm looking into making this into a configuration that can be switched in the `main.cpp` code. Maybe a struct or something, I have to read more about it.

The extra steps I had to do while troubleshooting were:

1. Ensure the drum brain firmware is the latest via https://harmonix.zendesk.com/hc/en-us/articles/218238387-How-To-Update-Your-Xbox-One-MadCatz-Firmware
2. For the MadCatz brain, I had to invert the kick outputs for it to work
3. I changed the mappings to match the toy drums for my personal configuration

I want to clean up my branch to include these as options in the code.  e.g.

```cpp
// Compile code based on the drum brain type.
//   0 = PDP
//   1 = MadCatz
#define DRUM_BRAIN_TYPE 0
...
// Then where the code differs between brain types:

if (DRUM_BRAIN_TYPE == 0) 
{
  // Do something specific for PDP brain
}
else #maybe else if?
{
  // Do something specific for MadCatz
}
```

However, I don't know if this will bloat the code... Another option was to simply use

```cpp
// Enable if using MadCatz
# #define DRUM_BRAIN_MADCATZ
...
// Then where the code differs
#ifdef DRUM_BRAIN_MADCATZ
  // only compile code for MadCatz
#else
  // Only compile code for PDP
#endif
```

I will spend some time finding the best way to approach a more configurable solution without breaking your original implementation.

**Comment by cobuffs** [comment]
FWIW, I was able to follow this very easily to get a Alesis Nitro linked into a MadCatz brain. Thanks to both of you. The MidiMapping.tbl gave me some issues when it wasn't set to toy drum config, so I took it out.
